version: '2'

services:
  attempo-server:
    image: 'softwarevale/mobile-server:v1'
    restart: 'always'
    ports:
    - "5000:5000"
    environment:
      HOST: 192.168.1.121
      PORT: 5432
      DBUSER: postgres
      DBPASS: postgres
      DBNAME: attempo
      SERVER_DOMAIN: '127.0.0.1:5000'
    volumes:
      - '/tmp/attempo_docker_files:/server/utils/uploadImages'